all:
  hosts:
    ansible1:
      ansible_host: 172.19.0.2
      ansible_user: user
      ansible_ssh_pass: "{{ ansible1_ssh_pass }}"
      ansible_become_pass: "{{ ansible1_ssh_pass }}"
    ansible2:
      ansible_host: 172.19.0.3
      ansible_user: user
      ansible_ssh_pass: "{{ ansible2_ssh_pass }}"
      ansible_become_pass: "{{ ansible2_ssh_pass }}"
